import { Component, Inject, NgModule, AfterContentInit, AfterViewInit, OnChanges, Directive, OnInit, Input } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { PredictionResponse } from './PredictionResponse';
import { PredictionRequest } from './PredictionRequest';
import { ChartOptions, ChartType, ChartDataSets } from 'chart.js';
import { Label } from 'ng2-charts';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
})

export class HomeComponent  {

  private http;
  private baseUrl;

  public prediction: PredictionResponse;
  public predictionRequest: PredictionRequest = {
    Suburb: "Essendon",
    Rooms: 2,
    Type: "u",
    Method: "SP",
    PostCode: 3040,
    RegionName: "Western Metropolitan",
    PropertyCount: 9264,
    Distance: 8.8,
    CouncilArea: "Moonee Valley City Council"
  };

  constructor(_http: HttpClient, @Inject('BASE_URL') _baseUrl: string) {
    this.http = _http;
    this.baseUrl = _baseUrl;
  }

  AddOrSubtract(val: number) {
    if (val < 0) return "detracted";
    return "added";
  }

  Abs(val:number) {
    return Math.abs(val);
  }

  onSubmit(predictionRequest: PredictionRequest) {
    this.http.post(this.baseUrl + 'api/Prediction/PredictHousingValue', predictionRequest)
      .subscribe(result => {
        if (result.status != "Ok") {
          this.errorMessage = result.statusMessage;
          this.isError = true;
        }
        else {
          this.errorMessage = null;
          this.isError = false;
        }
        this.prediction = result;
        this.barChartData = [
          {
            data: [
              result.suburb,
              result.rooms,
              result.type,
              result.method,
              result.postcode,
              result.regionname,
              result.propertycount,
              result.distance,
              result.councilArea,
              result.month,
              result.year,
            ],
            label: 'Feature contribution'
          },
        ];
        console.log("Reply: " + JSON.stringify(this.prediction));


      },
        error => {
          this.prediction = null;
          this.httpError = error;
          this.isError = true;

          if (error.error instanceof ErrorEvent) {
            this.errorMessage = error.error.message;
            console.error('An error occurred:', error.error.message);
          } else {
            this.errorMessage = "There seems to be a problem. The response from the server was " + error.status + ", which is not a good sign. Please look over the input fields and correct any possible errors.";
            console.error(
              `Backend returned code ${error.status}, ` +
              `body was: ${error.error}`);
          }
        }
      );
  }

  scrollToResultsView(): void {
    this.scrollToElement(document.querySelector("#resultsView"));
  }

  scrollToElement($element): void {
    $element.scrollIntoView({ behavior: "smooth", block: "start", inline: "nearest" });
  }

  public httpError: HttpErrorResponse;
  public errorMessage: string;
  public isError: Boolean;

  public barChartData: ChartDataSets[] = [
    { data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], label: 'Feature contribution' },
  ];

  public barChartOptions: ChartOptions = {
    responsive: true,
  };
  public barChartLabels: Label[] = [
    'Suburb',
    'Rooms',
    'Type',
    'Method',
    'Post Code',
    'Region Name',
    'Property Count',
    'Distance',
    'Council Area',
    'Month',
    'Year',
  ];
  public barChartType: ChartType = 'horizontalBar';
  public barChartLegend = true;
  public barChartPlugins = [];

  public formData = {
    "Suburb": [
      "Reservoir",
      "Bentleigh East",
      "Mount Waverley",
      "Richmond",
      "Glen Waverley",
      "Craigieburn",
      "Preston",
      "Kew",
      "Glen Iris",
      "Brunswick",
      "Northcote",
      "South Yarra",
      "Brighton",
      "Hawthorn",
      "Balwyn North",
      "Coburg",
      "Camberwell",
      "Glenroy",
      "Cheltenham",
      "Essendon",
      "Brighton East",
      "Bundoora",
      "Mill Park",
      "Pascoe Vale",
      "Epping",
      "St Kilda",
      "Port Melbourne",
      "Malvern East",
      "Doncaster East",
      "Hoppers Crossing",
      "Thornbury",
      "Prahran",
      "Bentleigh",
      "Balwyn",
      "Yarraville",
      "Elwood",
      "Greensborough",
      "St Albans",
      "Surrey Hills",
      "Werribee",
      "Hawthorn East",
      "Toorak",
      "Moonee Ponds",
      "Frankston",
      "Mitcham",
      "Carnegie",
      "Hampton",
      "Doncaster",
      "Footscray",
      "Mulgrave",
      "Lalor",
      "Mentone",
      "Ascot Vale",
      "Brunswick West",
      "Newport",
      "Thomastown",
      "Keilor East",
      "South Morang",
      "Croydon",
      "Burwood",
      "Highett",
      "Armadale",
      "Maribyrnong",
      "Ringwood",
      "Williamstown",
      "Fawkner",
      "Blackburn",
      "Ivanhoe",
      "Beaumaris",
      "Point Cook",
      "Sunshine West",
      "Parkdale",
      "Kensington",
      "Fitzroy North",
      "Melbourne",
      "West Footscray",
      "Sunbury",
      "Templestowe Lower",
      "Malvern",
      "Sandringham",
      "Templestowe",
      "Mernda",
      "Greenvale",
      "Wheelers Hill",
      "Roxburgh Park",
      "Eltham",
      "Maidstone",
      "Sunshine",
      "South Melbourne",
      "Broadmeadows",
      "Strathmore",
      "Murrumbeena",
      "Brunswick East",
      "Noble Park",
      "Airport West",
      "Coburg North",
      "Blackburn South",
      "Hillside",
      "Rosanna",
      "Avondale Heights",
      "Nunawading",
      "Bulleen",
      "Montmorency",
      "Heidelberg Heights",
      "Ashburton",
      "Fitzroy",
      "Forest Hill",
      "Altona North",
      "Ringwood East",
      "Sunshine North",
      "Elsternwick",
      "Ormond",
      "Wantirna South",
      "North Melbourne",
      "Kew East",
      "Donvale",
      "Dingley Village",
      "Niddrie",
      "Gladstone Park",
      "Ashwood",
      "MacLeod",
      "Blackburn North",
      "Clifton Hill",
      "Canterbury",
      "Mordialloc",
      "Albert Park",
      "Oak Park",
      "Heathmont",
      "Abbotsford",
      "Burwood East",
      "Windsor",
      "Taylors Lakes",
      "Dandenong North",
      "Oakleigh South",
      "Collingwood",
      "Clayton",
      "Tullamarine",
      "Caulfield South",
      "Dandenong",
      "Heidelberg West",
      "Moorabbin",
      "Chadstone",
      "Black Rock",
      "Wollert",
      "Wyndham Vale",
      "Ferntree Gully",
      "Altona",
      "Box Hill",
      "Fairfield",
      "Clayton South",
      "Seddon",
      "Carlton North",
      "Wantirna",
      "Keysborough",
      "Mont Albert",
      "Springvale",
      "Hampton East",
      "Heidelberg",
      "Carlton",
      "Vermont",
      "Tarneit",
      "Seaford",
      "Boronia",
      "Flemington",
      "Braybrook",
      "Vermont South",
      "Hadfield",
      "McKinnon",
      "Oakleigh",
      "Deer Park",
      "Frankston South",
      "Westmeadows",
      "Berwick",
      "Edithvale",
      "Viewbank",
      "Mooroolbark",
      "Keilor Downs",
      "Watsonia",
      "Sydenham",
      "Aspendale",
      "Bayswater",
      "Doreen",
      "Chelsea",
      "Melton South",
      "Rowville",
      "Kingsville",
      "Oakleigh East",
      "Ardeer",
      "Southbank",
      "Taylors Hill",
      "Meadow Heights",
      "Caulfield North",
      "Aberfeldie",
      "Alphington",
      "Albion",
      "Ringwood North",
      "Balaclava",
      "Hughesdale",
      "Middle Park",
      "Caroline Springs",
      "Gisborne",
      "Eltham North",
      "Dallas",
      "Clarinda",
      "West Melbourne",
      "Glen Huntly",
      "Diamond Creek",
      "Ivanhoe East",
      "Carrum",
      "Altona Meadows",
      "Melton",
      "East Melbourne",
      "Kings Park",
      "Watsonia North",
      "Parkville",
      "Jacana",
      "Endeavour Hills",
      "Delahey",
      "Gowanbrae",
      "Keilor",
      "Spotswood",
      "Yallambie",
      "Briar Hill",
      "Bonbeach",
      "Carrum Downs",
      "Eaglemont",
      "Narre Warren",
      "Melton West",
      "Lower Plenty",
      "Doveton",
      "Brooklyn",
      "Essendon West",
      "Aspendale Gardens",
      "Cremorne",
      "Essendon North",
      "Knoxfield",
      "Cairnlea",
      "Croydon North",
      "Truganina",
      "Kingsbury",
      "Bayswater North",
      "South Kingsville",
      "Springvale South",
      "Kealba",
      "Bellfield",
      "Attwood",
      "Keilor Park",
      "Kilsyth",
      "Scoresby",
      "Deepdene",
      "Derrimut",
      "Huntingdale",
      "Wallan",
      "Pakenham",
      "Chelsea Heights",
      "Mickleham",
      "Croydon South",
      "Notting Hill",
      "Patterson Lakes",
      "Warrandyte",
      "Frankston North",
      "Chirnside Park",
      "Langwarrin",
      "Albanvale",
      "Burnside Heights",
      "Kurunjang",
      "St Helena",
      "Williamstown North",
      "Caulfield",
      "Princes Hill",
      "Seaholme",
      "Croydon Hills",
      "Caulfield East",
      "Macleod",
      "Hampton Park",
      "Campbellfield",
      "Cranbourne",
      "Plumpton",
      "Travancore",
      "Kooyong",
      "Ripponlea",
      "Lilydale",
      "Gardenvale",
      "Research",
      "Laverton",
      "Hallam",
      "Williams Landing",
      "Strathmore Heights",
      "Waterways",
      "Docklands",
      "Riddells Creek",
      "Keilor Lodge",
      "Burnley",
      "Burnside",
      "Cranbourne North",
      "Heatherton",
      "New Gisborne",
      "Warranwood",
      "Coolaroo",
      "Manor Lakes",
      "Cranbourne West",
      "Beaconsfield",
      "The Basin",
      "Bacchus Marsh",
      "Skye",
      "Plenty",
      "Seabrook",
      "North Warrandyte",
      "Wonga Park",
      "Diggers Rest",
      "Cranbourne East",
      "Officer",
      "Rockbank",
      "Eumemmerring",
      "Emerald",
      "Wattle Glen",
      "Brookfield",
      "Lysterfield",
      "Mount Evelyn",
      "Sandhurst",
      "Healesville",
      "Tecoma",
      "Upwey",
      "Clyde North",
      "Montrose",
      "Lynbrook",
      "Whittlesea",
      "Hurstbridge",
      "Lyndhurst",
      "Bullengarook",
      "Oaklands Junction",
      "Werribee South",
      "Beaconsfield Upper",
      "Eynesbury",
      "Bulla",
      "Gisborne South",
      "Monbulk",
      "Darley",
      "Coldstream",
      "Botanic Ridge",
      "Kalkallo",
      "Silvan",
      "Yarra Glen",
      "Yan Yean",
      "Ferny Creek",
      "Woori Yallock",
      "Mount Dandenong",
      "Panton Hill",
      "Park Orchards",
      "Chintin",
      "Olinda",
      "Kilsyth South",
      "Cranbourne South",
      "Belgrave",
      "Seville",
      "Cockatoo",
      "Warburton",
      "Kallista",
      "Guys Hill",
      "Kalorama",
      "Don Valley",
      "Toolern Vale",
      "croydon",
      "Avonsleigh",
      "viewbank",
      "Yarra Junction",
      "Maddingley",
      "Wildwood",
      "Warrandyte South",
      "Gembrook",
      "Menzies Creek",
      "Belgrave South",
      "Pentland Hills",
      "Hopetoun Park",
      "Yarrambat",
      "Belgrave Heights",
      "Castella",
      "Lysterfield South",
      "Wandin North",
      "Warneet"
    ],
    "Type": [
      "h",
      "u",
      "t"
    ],
    "Method": [
      "S",
      "PI",
      "SP",
      "VB",
      "SN",
      "PN",
      "W",
      "SA",
      "SS"
    ],
    "Postcode": [
      3073,
      3064,
      3150,
      3121,
      3046,
      3020,
      3165,
      3149,
      3058,
      3204,
      3030,
      3040,
      3130,
      3012,
      3163,
      3195,
      3032,
      3072,
      3029,
      3101,
      3146,
      3181,
      3056,
      3083,
      3070,
      3141,
      3186,
      3122,
      3104,
      3084,
      3021,
      3124,
      3192,
      3187,
      3127,
      3082,
      3037,
      3145,
      3044,
      3088,
      3011,
      3199,
      3188,
      3076,
      3182,
      3207,
      3109,
      3042,
      3103,
      3015,
      3068,
      3193,
      3071,
      3136,
      3043,
      3081,
      3131,
      3031,
      3134,
      3013,
      3184,
      3047,
      3147,
      3166,
      3079,
      3754,
      3135,
      3123,
      3142,
      3039,
      3196,
      3132,
      3108,
      3170,
      3095,
      3075,
      3194,
      3152,
      3055,
      3016,
      3023,
      3175,
      3033,
      3074,
      3041,
      3752,
      3038,
      3125,
      3190,
      3143,
      3060,
      3144,
      3085,
      3133,
      3000,
      3429,
      3107,
      3206,
      3191,
      3106,
      3078,
      3059,
      3205,
      3172,
      3185,
      3057,
      3174,
      3169,
      3034,
      3105,
      3094,
      3168,
      3065,
      3087,
      3025,
      3051,
      3162,
      3102,
      3111,
      3337,
      3018,
      3049,
      3126,
      3054,
      3067,
      3153,
      3151,
      3167,
      3066,
      3024,
      3156,
      3189,
      3148,
      3750,
      3128,
      3173,
      3171,
      3053,
      3198,
      3155,
      3019,
      3806,
      3138,
      3338,
      3048,
      3197,
      3178,
      3028,
      3006,
      3022,
      3161,
      3437,
      3183,
      3977,
      3003,
      3089,
      3002,
      3052,
      3802,
      3036,
      3177,
      3201,
      3805,
      3093,
      3180,
      3137,
      3113,
      3179,
      3756,
      3810,
      3200,
      3116,
      3910,
      3335,
      3061,
      3976,
      3140,
      3803,
      3027,
      3008,
      3431,
      3340,
      3202,
      3438,
      3807,
      3154,
      3090,
      3975,
      3115,
      3782,
      3160,
      3427,
      3809,
      3096,
      3796,
      3777,
      3978,
      3139,
      3765,
      3158,
      3757,
      3099,
      3063,
      3808,
      3428,
      3793,
      3775,
      3795,
      3755,
      3770,
      3759,
      3786,
      3114,
      3767,
      3799,
      3788,
      3781,
      3783,
      3980,
      3791,
      3766,
      3797,
      3341,
      3159,
      3091
    ],
    "Regionname": [
      "Southern Metropolitan",
      "Northern Metropolitan",
      "Western Metropolitan",
      "Eastern Metropolitan",
      "South-Eastern Metropolitan",
      "Eastern Victoria",
      "Northern Victoria",
      "Western Victoria"
    ],
    "CouncilArea": [
      "Boroondara City Council",
      "Darebin City Council",
      "Banyule City Council",
      "Monash City Council",
      "Bayside City Council",
      "Brimbank City Council",
      "Moreland City Council",
      "Hume City Council",
      "Glen Eira City Council",
      "Melbourne City Council",
      "Whittlesea City Council",
      "Moonee Valley City Council",
      "Kingston City Council",
      "Manningham City Council",
      "Maribyrnong City Council",
      "Stonnington City Council",
      "Whitehorse City Council",
      "Port Phillip City Council",
      "Yarra City Council",
      "Wyndham City Council",
      "Maroondah City Council",
      "Hobsons Bay City Council",
      "Knox City Council",
      "Greater Dandenong City Council",
      "Frankston City Council",
      "Melton City Council",
      "Casey City Council",
      "Nillumbik Shire Council",
      "Yarra Ranges Shire Council",
      "Macedon Ranges Shire Council",
      "Cardinia Shire Council",
      "Mitchell Shire Council",
      "Moorabool Shire Council",
      "Murrindindi Shire Council"
    ]
  };
}


